name: Mi primer GitHub Action

on:
  push:

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar programa
        run: python main.py
